#!/usr/bin/env node
import { randomBytes, createCipheriv } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'referral-links.txt');
const OUT = join(root, 'electron', 'system', 'referral-pool.gen.ts');

const POOL_KEY_HEX =
  'c1b7e69a4d20f3585b8e17d2a94c6e0f7d31a8c25e94b06fd8427c1a90e5b3f6';

if (!existsSync(SRC)) {
  console.error(`missing ${SRC} — create it with one referral URL per line`);
  process.exit(1);
}

const links = readFileSync(SRC, 'utf-8')
  .split(/\r?\n/)
  .map((l) => l.trim())
  .filter((l) => l && !l.startsWith('#'))
  .flatMap((l) => {
    const m = l.match(/^(\S+)\s+x(\d+)$/i);
    if (!m) return [l];
    return Array(Math.max(1, Number(m[2]))).fill(m[1]);
  });

const bad = links.filter((l) => !/^https:\/\/kalshi\.com\/(r\/[\w-]+|sign-up\/?\?referral=[\w-]+)$/i.test(l));
if (bad.length) {
  console.error('rejected non-Kalshi-referral lines:\n  ' + bad.join('\n  '));
  process.exit(1);
}
if (links.length === 0) {
  console.error('referral-links.txt has no links');
  process.exit(1);
}

const iv = randomBytes(12);
const cipher = createCipheriv('aes-256-gcm', Buffer.from(POOL_KEY_HEX, 'hex'), iv);
const ct = Buffer.concat([cipher.update(JSON.stringify(links), 'utf-8'), cipher.final()]);
const blob = Buffer.concat([iv, cipher.getAuthTag(), ct]).toString('base64');

writeFileSync(
  OUT,
  '// GENERATED by scripts/referrals.mjs — do not edit. Encrypted referral pool\n' +
  '// (AES-256-GCM: 12-byte IV | 16-byte tag | ciphertext, base64).\n' +
  `export const REFERRAL_POOL_ENC = '${blob}';\n`,
  'utf-8',
);
console.log(`encrypted ${links.length} referral link(s) -> ${OUT}`);
